import { commandStructureOf } from "./utils/commandStructure";

export function textual(command: string) {
    const c = commandStructureOf(command);

    return ({
        vim: "Real programmers use notepad",
        vi: "Real programmers use notepad",
        emacs: "Real programmers use notepad",
        chmod: "Invalid identifier",
        mkdir: "",
        pwd: "/usr/root/servers/osjs/repo/dist/backend/bundles/js/index/node_modules/express",
        kill: "that's illegal",
        killall: "that's illegal",
        more: "less is more",
        less: "more or less",
        nice: "thanks",
        printf: "\\0",
        sed: "Invalid argument",
        sleep: "zzz",
        time: "wow",
        what: "what?",
        whoami: "name",
        sudo: "fine",
        find: "We don't have any",
        alias: "echo",
        date: "Sun 10 Mar 2021 15:40:03 EDT",
        diff: "Incomparable",
        false: "true",
        true: "true",
        head: "Invalid argume",
        tail: "lid argument",
        awk: "We don't have any",
        blockchain: "yep we use that",
        logout: "you're here forever",
        mv: "Invalid argument",
        cp: "Invalid argument",
        rm: "rm: is a directory",
        rmdir: "Error: rmdir is a directory",
        nano: "nice",
        npm: "There's a new minor update for yarn.\nType yarn i -g npm to update.",
        yarn: "There's a new minor update for npm.\nType npm i -g npm to update.",
        nvm: "Currently using node v14.0.7.",
        node: "Error: ENOENT",
        cat: "meow",
        ls: "/usr\n/root\n/www",
        wow: "wow!",
        ssh: "ssh: Could not resolve hostname",
        "apt-get": "installing...",
        apt: "installing...",
        source: "",
        xkcd: "404",
        bash: "bash is not supported. Use node instead.",
        sh: "sh is not supported. Use node instead.",
        gcc: "gcc is not supported. Use node instead.",
        ruby: "ruby is not supported. Use node instead.",
        python: "python is not supported. Use node instead.",
        pip: "pip is not supported. Use node instead.",
        python2: "python2 is not supported. Use node instead.",
        python3: "python3 is not supported. Use node instead.",
        rust: "rust is not supported. Use node instead.",
        java: "java is not supported. Use node instead.",
        javascript: "javascript is not supported. Use node instead.",
        js: "js is not supported. Use node instead.",
        kotlin: "kotlin is not supported. Use node instead.",
        go: "go is not supported. Use node instead.",
        sql: "sql is not supported. Use node instead.",
        mysql: "mysql is not supported. Use node instead.",
        php: "php is not supported. Use node instead.",
        vb: "vb is not supported. Use node instead.",
        swift: "swift is not supported. Use node instead.",
        scala: "scala is not supported. Use node instead.",
        scheme: "scheme is not supported. Use node instead.",
        racket: "racket is not supported. Use node instead.",
        "g++": "g++ is not supported. Use node instead.",
        clang: "clang is not supported. Use node instead.",
        gdb: "gdb is not supported. Use node instead.",
        stop: "sorry",
        restart: "You don't need to start jsos manually! Instead, just wait for it to crash.",
        help: "jsos supports \"most\" unix commands.\n"
            + "Additionally, \"say [message]\" sends a message to everyone.\n"
            + "For more information about how to use a command, type \"man [command]\".\n",
        "\"help\"": "Very funny. Without the quotes, please.",
        grep: "Found 9 results",
        git: "fatal: The current branch test has no upstream branch.\nTo push the current branch and set the remote as upstream, use\n\n    git push --set-upstream ugh\n",
    } as any)[c.name];
}
